/* =====================================================================
   DATA — everything editable lives here
   ===================================================================== */
const NAV = [
  ["HOME", "#home"],
  ["SYSTEM", "#system"],
  ["3D TWIN", "#twin"],
  ["SIM", "#simlab"],
  ["CONTROL", "#control"],
  ["SENSING", "#sensing"],
  ["DECISION", "#brain"],
  ["COMPONENTS", "#components"],
  ["JOURNEY", "#journey"],
  ["REVIEWS", "#reviews"],
  ["TEAM", "#team"],
  ["FUTURE", "#future"],
  ["CONTACT", "#contact"],
];

const PROBLEM = [
  "Low oxygen availability",
  "Poor or contaminated air quality",
  "Limited breathable atmosphere",
  "High respiratory workload",
  "Need for controlled O₂ supplementation",
];
const SOLUTION = [
  "Filtered breathing air",
  "Positive-pressure respiratory support",
  "Controlled O₂ supplementation",
  "Exhaled-gas recycling",
  "CO₂ removal & moisture management",
  "Real-time sensing & adaptive control",
  "Fail-safe monitoring",
];

const SPECS = [
  /* INITIAL DESIGN TARGETS / CONCEPT VALUES */
  ["Design airflow", "≈ 30", "L/min"],
  ["Blower capability", "≈ 70", "Pa"],
  ["Operating pressure", "2 – 5", "cmH₂O"],
  ["O₂ cylinder", "2", "L"],
  ["Cylinder pressure", "200", "bar"],
  ["Electrical load", "≈ 10.7", "W"],
  ["Preliminary runtime", "≈ 7 – 8", "hours"],
];

const COMPONENTS = [
  {
    id: "filter",
    name: "Air Filter",
    icon: "M4 5h16v3l-6 5v6l-4-2v-4L4 8Z",
    fn: "Removes particulates & contaminants from ambient intake.",
    prin: "HEPA / particulate media traps particles before they reach the blower.",
    in: "Ambient air",
    out: "Filtered air",
    sensor: "—",
    ctrl: "Blockage inferred via pressure/flow drop",
    specs: "HEPA / particulate class · low pressure drop",
    mat: "Pleated media, molded housing",
  },
  {
    id: "blower",
    name: "Variable-Speed Blower",
    icon: "M12 12m-3 0a3 3 0 106 0 3 3 0 10-6 0M12 3v3M12 18v3M3 12h3M18 12h3",
    fn: "Generates positive-pressure airflow into the loop.",
    prin: "Centrifugal impeller driven at variable speed to hold target pressure.",
    in: "Filtered air",
    out: "Pressurized air",
    sensor: "Pressure, flow feedback",
    ctrl: "PWM speed control from ESP32",
    specs: "≈ 70 Pa · variable RPM · ~30 L/min target",
    mat: "Composite impeller, BLDC motor",
  },
  {
    id: "mixing",
    name: "Mixing Chamber",
    icon: "M6 4h12v4a6 6 0 01-12 0Z M8 20h8",
    fn: "Blends fresh air, recycled gas and supplemental O₂.",
    prin: "Controlled volume where three streams homogenize before delivery.",
    in: "Fresh air + recycled gas + O₂",
    out: "Conditioned breathing gas",
    sensor: "O₂, CO₂, pressure",
    ctrl: "Balances recycle ratio & O₂ dose",
    specs: "Sealed chamber · 2–5 cmH₂O support",
    mat: "Polycarbonate body",
  },
  {
    id: "mask",
    name: "Respiratory Mask",
    icon: "M4 9c0-3 4-4 8-4s8 1 8 4c0 5-3 9-8 9s-8-4-8-9Z M9 20h6",
    fn: "User interface delivering conditioned gas & collecting exhalation.",
    prin: "Anatomical silicone seal with separate inhalation / exhalation ports.",
    in: "Conditioned gas",
    out: "Exhaled gas to recycle loop",
    sensor: "Pressure at interface",
    ctrl: "Positive-pressure support delivery",
    specs: "Silicone seal · dual-port · pressure-support connector",
    mat: "Medical silicone, polycarbonate ports",
  },
  {
    id: "cylinder",
    name: "Oxygen Cylinder",
    icon: "M9 3h6v2l-1 1v13a2 2 0 01-4 0V6L9 5Z",
    fn: "Stores high-pressure medical oxygen reserve.",
    prin: "Compressed O₂ released through the regulator on demand.",
    in: "—",
    out: "High-pressure O₂",
    sensor: "Cylinder pressure",
    ctrl: "Reserve monitored for endurance",
    specs: "2 L · 200 bar (concept)",
    mat: "Aluminium / composite cylinder",
  },
  {
    id: "reg",
    name: "Pressure Regulator",
    icon: "M12 4v4M6 12a6 6 0 1112 0 M12 12l3 3",
    fn: "Steps cylinder pressure down to a safe working pressure.",
    prin: "Spring-loaded regulation delivers stable downstream pressure.",
    in: "High-pressure O₂",
    out: "Regulated O₂",
    sensor: "Downstream pressure",
    ctrl: "Sets safe supply to valve",
    specs: "200 bar → working pressure",
    mat: "Brass / stainless body",
  },
  {
    id: "valve",
    name: "O₂ Control Valve",
    icon: "M4 12h6l2-4 2 8 2-4h2",
    fn: "Meters supplemental oxygen into the mixing chamber.",
    prin: "Proportional / solenoid valve pulsed to dose O₂ on demand.",
    in: "Regulated O₂",
    out: "Metered O₂",
    sensor: "O₂ concentration feedback",
    ctrl: "PWM / pulse from ESP32 (demand-based)",
    specs: "Proportional · fast response",
    mat: "Solenoid actuator",
  },
  {
    id: "oneway",
    name: "One-Way Valve",
    icon: "M5 12h9l-3-3M14 12l-3 3M17 6v12",
    fn: "Enforces single-direction exhaled-gas flow.",
    prin: "Check valve prevents backflow into the mask.",
    in: "Exhaled gas",
    out: "Directed exhaled gas",
    sensor: "—",
    ctrl: "Passive safety element",
    specs: "Low cracking pressure",
    mat: "Silicone flap / polymer",
  },
  {
    id: "moist",
    name: "Moisture Separator",
    icon: "M12 3s6 7 6 11a6 6 0 01-12 0c0-4 6-11 6-11Z",
    fn: "Removes humidity from exhaled gas before scrubbing.",
    prin: "Condenses and traps water droplets from the warm exhaled stream.",
    in: "Exhaled gas",
    out: "De-humidified gas",
    sensor: "Humidity",
    ctrl: "Protects scrubber efficiency",
    specs: "Coalescing / condensate trap",
    mat: "Hydrophobic media",
  },
  {
    id: "scrub",
    name: "CO₂ Scrubber",
    icon: "M6 6h12v12H6zM9 9h6v6H9z",
    fn: "Chemically removes carbon dioxide from recycled gas.",
    prin: "Sorbent media (e.g. soda-lime type) captures CO₂ as gas passes through.",
    in: "De-humidified gas",
    out: "Low-CO₂ conditioned gas",
    sensor: "CO₂ concentration",
    ctrl: "Recycle ratio adjusted on CO₂ rise",
    specs: "Replaceable sorbent cartridge",
    mat: "CO₂-absorbent granules",
  },
  {
    id: "recirc",
    name: "Recirculation Blower",
    icon: "M12 12m-3 0a3 3 0 106 0 3 3 0 10-6 0M12 3v3M12 18v3M3 12h3M18 12h3",
    fn: "Re-pressurises scrubbed, dried recycled gas and drives it back into the mixing chamber.",
    prin: "A second variable-speed blower downstream of the CO₂ scrubber and moisture separator restores the pressure lost across the recycle loop, so enough gas returns to the mask.",
    in: "Low-CO₂, de-humidified recycled gas",
    out: "Pressurised recycled gas",
    sensor: "Loop pressure & flow feedback",
    ctrl: "PWM speed control from ESP32 — holds loop pressure & tops up with O₂ when recycled volume is low",
    specs: "Variable RPM · recycle-loop booster",
    mat: "Composite impeller, BLDC motor",
  },
  {
    id: "esp",
    name: "ESP32 Controller",
    icon: "M7 7h10v10H7zM9 3v4M15 3v4M9 17v4M15 17v4M3 9h4M3 15h4M17 9h4M17 15h4",
    fn: "The decision-making core of the loop.",
    prin: "Reads all sensors, runs control algorithms & safety logic, drives actuators.",
    in: "All sensor signals",
    out: "Blower PWM · O₂ valve · alarms",
    sensor: "All 7 channels",
    ctrl: "Acquisition · decision · logging · safety",
    specs: "Dual-core MCU · Wi-Fi/BLE capable",
    mat: "PCB module + enclosure",
  },
  {
    id: "sensors",
    name: "Sensor Suite",
    icon: "M12 3a9 9 0 100 18 9 9 0 000-18ZM12 8v4l3 2",
    fn: "Continuous measurement of the gas & environment.",
    prin: "Seven channels sampled continuously for closed-loop control.",
    in: "Gas & environment",
    out: "Digital/analog signals to ESP32",
    sensor: "O₂·CO₂·P·flow·T·RH·cyl",
    ctrl: "Feeds decision engine",
    specs: "7-channel continuous monitoring",
    mat: "Mixed sensor modules",
  },
];

// Physical parts of the wearable full-face mask — used by the 3D digital twin & its labels.
const MASK_PARTS = [
  {
    id: "shell",
    name: "Oronasal Mask Shell",
    fn: "Rigid full-face shell that houses the assembly and seals to the face.",
    prin: "Matte-grey Nylon/PETG structure holds the visor, valves and cartridges and forms the sealed breathing cavity.",
    in: "—",
    out: "—",
    sensor: "Interface pressure",
    ctrl: "Positive-pressure support delivery",
    specs: "Nylon / PETG · oronasal full-face",
    mat: "Matte-grey Nylon/PETG + silicone face seal",
  },
  {
    id: "visor",
    name: "Visor",
    fn: "Clear panoramic window over the eyes and nose.",
    prin: "Anti-fog transparent panel maintains field of view inside the sealed cavity.",
    in: "—",
    out: "—",
    sensor: "—",
    ctrl: "—",
    specs: "Transparent polycarbonate",
    mat: "Polycarbonate",
  },
  {
    id: "hepafilter",
    name: "HEPA + Activated Carbon Filter",
    fn: "Filters ambient (bunker) air of particulates and contaminants on intake.",
    prin: "HEPA media traps particles; activated carbon adsorbs gases/odours before air enters the loop.",
    in: "Ambient air",
    out: "Filtered fresh air",
    sensor: "Blockage inferred via pressure/flow",
    ctrl: "—",
    specs: "Replaceable round cartridge · HEPA + carbon",
    mat: "HEPA media + activated carbon",
  },
  {
    id: "inhaleport",
    name: "Inhalation Port & Filter",
    fn: "One-way inhalation path delivering filtered fresh air into the cavity.",
    prin: "Check valve opens on inhalation, drawing conditioned gas toward the user.",
    in: "Filtered / conditioned gas",
    out: "Inhaled gas",
    sensor: "Flow",
    ctrl: "—",
    specs: "One-way inhalation valve",
    mat: "Silicone flap + polymer housing",
  },
  {
    id: "exhalevalve",
    name: "Exhalation Valve",
    fn: "One-way outlet that vents exhaled gas from the cavity.",
    prin: "Cross-vented check valve opens on exhalation, directing gas to the recycle path.",
    in: "Exhaled gas",
    out: "Directed exhaled gas",
    sensor: "—",
    ctrl: "—",
    specs: "Cross-vent one-way valve",
    mat: "Silicone diaphragm",
  },
  {
    id: "co2scrub",
    name: "CO₂ Scrubber Cartridge",
    fn: "Removes carbon dioxide from exhaled gas so it can be re-breathed.",
    prin: "Soda-lime absorbent captures CO₂ as gas passes through the clear replaceable cartridge.",
    in: "Exhaled gas",
    out: "Low-CO₂ conditioned gas",
    sensor: "CO₂ concentration",
    ctrl: "Recycle ratio adjusted on CO₂ rise",
    specs: "Replaceable · soda-lime absorbent",
    mat: "Soda-lime granules in clear canister",
  },
  {
    id: "mixport",
    name: "Mixing Chamber Port",
    fn: "Where fresh, recycled and O₂ streams converge before delivery.",
    prin: "Blends the three gas streams to the target O₂/CO₂ balance inside the mask.",
    in: "Fresh + recycled + O₂",
    out: "Conditioned breathing gas",
    sensor: "O₂, CO₂, pressure",
    ctrl: "Balances recycle ratio & O₂ dose",
    specs: "Integrated mixing volume",
    mat: "Polymer housing",
  },
  {
    id: "o2inlet",
    name: "Demand-Based Oxygen Inlet",
    fn: "Injects supplemental oxygen only when demanded.",
    prin: "Controllable valve pulses O₂ from the backpack cylinder into the mix on demand.",
    in: "Regulated O₂",
    out: "Metered O₂",
    sensor: "O₂ concentration feedback",
    ctrl: "PWM / pulse from ESP32",
    specs: "Demand valve · fast response",
    mat: "Solenoid / proportional valve",
  },
  {
    id: "hose",
    name: "Flexible Breathing Hose",
    fn: "Connects the mask to the backpack life-support unit.",
    prin: "Corrugated medical hose carries gas between the mask and the blower/cylinder backpack.",
    in: "—",
    out: "—",
    sensor: "—",
    ctrl: "—",
    specs: "Flexible corrugated tubing",
    mat: "Medical-grade corrugated polymer",
  },
  {
    id: "harness",
    name: "Head Harness",
    fn: "Four-point strap system that holds the mask sealed to the face.",
    prin: "Adjustable straps distribute clamping force for a reliable seal.",
    in: "—",
    out: "—",
    sensor: "—",
    ctrl: "—",
    specs: "4-point adjustable harness",
    mat: "Elastic webbing + buckles",
  },
];
// Merged lookup for 3D labels & click-to-open panels.
const PART_INFO = {};
[...COMPONENTS, ...MASK_PARTS].forEach((c) => {
  PART_INFO[c.id] = c;
});

const SENSORS = [
  {
    n: "O₂ Sensor",
    u: "%",
    p: "Oxygen concentration in the mix",
    icon: "M12 3a9 9 0 100 18 9 9 0 000-18ZM12 7v10",
  },
  {
    n: "CO₂ Sensor",
    u: "ppm",
    p: "Carbon dioxide level after scrubbing",
    icon: "M4 8h16M4 16h16M8 4v16",
  },
  {
    n: "Pressure Sensor",
    u: "cmH₂O / Pa",
    p: "Circuit & support pressure",
    icon: "M12 4v4M6 12a6 6 0 1112 0M12 12l3 2",
  },
  {
    n: "Flow Sensor",
    u: "L/min",
    p: "Airflow through the circuit",
    icon: "M4 12h6l2-5 2 10 2-5h2",
  },
  {
    n: "Temperature",
    u: "°C",
    p: "Gas & environment temperature",
    icon: "M12 4a2 2 0 00-2 2v8a4 4 0 104 0V6a2 2 0 00-2-2Z",
  },
  {
    n: "Humidity",
    u: "%RH",
    p: "Moisture content of the gas",
    icon: "M12 3s6 7 6 11a6 6 0 01-12 0c0-4 6-11 6-11Z",
  },
  {
    n: "Cylinder Pressure",
    u: "bar",
    p: "Remaining O₂ reserve",
    icon: "M9 3h6v2l-1 1v13a2 2 0 01-4 0V6L9 5Z",
  },
];

const MODES = [
  { id: "normal", label: "Normal Breathing" },
  { id: "demand", label: "High Demand" },
  { id: "lowo2", label: "Low O₂" },
  { id: "highco2", label: "High CO₂" },
  { id: "blockage", label: "Filter Blockage" },
  { id: "sensorfail", label: "Sensor Failure" },
  { id: "failsafe", label: "Fail-Safe" },
];

const TIMELINE = [
  [
    "01",
    "Problem Identification",
    "Defined the need for respiratory support in extreme, low-oxygen environments.",
  ],
  [
    "02",
    "Literature Review",
    "Surveyed closed-circuit breathing, altitude physiology & life-support systems.",
  ],
  [
    "03",
    "Concept Development",
    "Framed the semi-closed adaptive loop: assist · recycle · supplement.",
  ],
  [
    "04",
    "System Architecture",
    "Mapped breathing circuit, recycle loop and control layer end-to-end.",
  ],
  [
    "05",
    "Component Selection",
    "Chose blower, valve, sensors, scrubber media and the ESP32 platform.",
  ],
  [
    "06",
    "Mechanical Design",
    "Designed chamber, tubing routing and mask interface.",
  ],
  ["07", "Electronic System", "Built the sensing & ESP32 control hardware."],
  [
    "08",
    "Control Algorithm",
    "Developed adaptive decision logic & fail-safe rules.",
  ],
  [
    "09",
    "Prototype Development",
    "Assembling and wiring the working prototype.",
  ],
  ["10", "Testing & Validation", "Bench trials against the design targets."],
  ["11", "Optimization", "Tuning efficiency, endurance and ergonomics."],
  [
    "12",
    "Final Demonstration",
    "Integrated system demonstration & documentation.",
  ],
];

// NOTE: no academic review has been conducted yet — these are editable templates.
// Set status to 'wip' (In Progress) or 'done' (Completed) and fill the fields as reviews happen.
const REVIEWS = [
  {
    n: "Zeroth Review",
    date: "To be scheduled",
    status: "up",
    obj: "Establish the problem statement, scope and objectives.",
    work: ["To be documented"],
    add: "To be added",
    chal: "To be added",
    sol: "To be added",
    fac: "To be added after the review",
    chg: "To be added",
    next: "Present concept & architecture at the First Review",
  },
  {
    n: "First Review",
    date: "To be scheduled",
    status: "up",
    obj: "Present the concept and system architecture.",
    work: ["To be documented"],
    add: "To be added",
    chal: "To be added",
    sol: "To be added",
    fac: "To be added after the review",
    chg: "To be added",
    next: "Component selection & prototyping",
  },
  {
    n: "Second Review",
    date: "To be scheduled",
    status: "up",
    obj: "Component selection and subsystem prototyping.",
    work: ["To be documented"],
    add: "To be added",
    chal: "To be added",
    sol: "To be added",
    fac: "To be added after the review",
    chg: "To be added",
    next: "Integration & closed-loop testing",
  },
  {
    n: "Third Review",
    date: "To be scheduled",
    status: "up",
    obj: "Full integration and closed-loop validation.",
    work: ["To be documented"],
    add: "To be added",
    chal: "To be added",
    sol: "To be added",
    fac: "To be added after the review",
    chg: "To be added",
    next: "Optimization & final build",
  },
  {
    n: "Final Review",
    date: "To be scheduled",
    status: "up",
    obj: "Final demonstration and documentation.",
    work: ["To be documented"],
    add: "To be added",
    chal: "To be added",
    sol: "To be added",
    fac: "To be added after the review",
    chg: "To be added",
    next: "Project close-out",
  },
];

// Editable status estimates — early-stage. Update as work progresses.
const WORK = [
  ["Concept Design", 45],
  ["System Architecture", 40],
  ["Airflow Circuit", 20],
  ["Oxygen Supplementation", 15],
  ["Gas Recycling", 15],
  ["CO₂ Removal", 10],
  ["Sensor Integration", 10],
  ["ESP32 Programming", 10],
  ["Control Logic", 10],
  ["3D Modelling", 25],
  ["Prototype Fabrication", 5],
  ["Testing", 0],
];

const LIT = [
  {
    t: "Closed-circuit breathing apparatus — principles",
    a: "Placeholder authors",
    j: "Journal placeholder",
    y: "20XX",
    doi: "10.xxxx/placeholder",
    k: "CO₂ scrubbing & gas recycling fundamentals",
    r: "Basis for our recycle loop",
  },
  {
    t: "Adaptive oxygen delivery in hypoxic environments",
    a: "Placeholder authors",
    j: "Journal placeholder",
    y: "20XX",
    doi: "10.xxxx/placeholder",
    k: "Demand-based O₂ conserves reserve",
    r: "Informs demand-based valve control",
  },
  {
    t: "Embedded control for portable respiratory devices",
    a: "Placeholder authors",
    j: "Journal placeholder",
    y: "20XX",
    doi: "10.xxxx/placeholder",
    k: "MCU-based closed-loop feasibility",
    r: "Supports ESP32 control approach",
  },
  {
    t: "Positive-pressure support & breathing effort",
    a: "Placeholder authors",
    j: "Journal placeholder",
    y: "20XX",
    doi: "10.xxxx/placeholder",
    k: "2–5 cmH₂O reduces work of breathing",
    r: "Sets our support pressure band",
  },
];

const COMPARE = [
  ["Adaptability", "no", "yes"],
  ["Gas recycling", "no", "yes"],
  ["Oxygen optimization", "mid", "yes"],
  ["Environmental monitoring", "no", "yes"],
  ["Real-time control", "mid", "yes"],
  ["Portability potential", "mid", "yes"],
  ["Extreme-environment suitability", "no", "yes"],
];

const FUTURE = [
  "Complete physical prototype fabrication",
  "Advanced CFD airflow analysis",
  "CFD: pressure drop, velocity, resistance & mixing",
  "Real-time sensor integration",
  "Embedded control algorithm development",
  "AI-based respiratory demand prediction",
  "Automatic oxygen optimization",
  "Compact wearable design",
  "Lightweight component optimization",
  "Battery optimization",
  "Clinical simulation testing",
  "Extreme-environment testing",
  "Digital twin development",
  "IoT remote monitoring",
  "Mobile application integration",
];

const FAULTS = [
  {
    n: "High CO₂",
    crit: false,
    det: "CO₂ sensor above threshold",
    res: "Increase fresh air, reduce recycle ratio",
    act: "Flush loop with filtered air",
    alm: "Amber alert",
  },
  {
    n: "Low O₂",
    crit: false,
    det: "O₂ concentration below band",
    res: "Open O₂ valve wider",
    act: "Increase supplementation",
    alm: "Amber alert",
  },
  {
    n: "High Pressure",
    crit: false,
    det: "Circuit pressure above 5 cmH₂O",
    res: "Reduce blower speed",
    act: "Relieve to safe band",
    alm: "Amber alert",
  },
  {
    n: "Low Pressure",
    crit: false,
    det: "Circuit pressure below 2 cmH₂O",
    res: "Increase blower speed",
    act: "Restore support",
    alm: "Amber alert",
  },
  {
    n: "Sensor Failure",
    crit: true,
    det: "Implausible / lost sensor signal",
    res: "Enter fail-safe, use safe defaults",
    act: "Maintain fresh-air delivery",
    alm: "Critical alarm",
  },
  {
    n: "Blower Failure",
    crit: true,
    det: "No flow / RPM feedback lost",
    res: "Fail-safe, open path for spontaneous breathing",
    act: "Ensure user can breathe",
    alm: "Critical alarm",
  },
  {
    n: "Oxygen Supply Failure",
    crit: true,
    det: "Cylinder pressure critically low",
    res: "Alert & conserve, prioritise air",
    act: "Notify user to switch reserve",
    alm: "Critical alarm",
  },
  {
    n: "Battery Low",
    crit: false,
    det: "Pack voltage below reserve",
    res: "Reduce non-essential loads",
    act: "Prompt recharge / swap",
    alm: "Amber alert",
  },
];

const TEAM = [
  {
    init: "HP",
    name: "Harikant Prasad Gupta",
    role: "Biomedical Engineering",
    bio: "System design, research and development — architecture, ESP32 control and the closed-loop pipeline.",
    skills: ["System Design", "ESP32", "Control Logic", "Sensing"],
    id: "ARS-001",
  },
  {
    init: "SK",
    name: "Sahil Krishna",
    role: "Biomedical Engineering",
    bio: "System design, research and development — breathing circuit, mixing chamber and recycle-loop hardware.",
    skills: ["Mechanical", "Airflow", "CAD", "Prototyping"],
    id: "ARS-002",
  },
  {
    init: "KT",
    name: "Kinley Khamsum Tshering",
    role: "Biomedical Engineering",
    bio: "System design, research and development — power, O₂ supplementation and the fail-safe & alarm subsystems.",
    skills: ["Power", "O₂ Control", "Safety", "Testing"],
    id: "ARS-003",
  },
];

const GALLERY = [
  ["Concept Design", "Ideation", 180],
  ["System Architecture", "Block diagram", 240],
  ["3D Models", "Digital twin", 200],
  ["Component Selection", "Hardware", 160],
  ["Prototype Development", "Build", 260],
  ["Testing", "Bench", 190],
  ["Review Presentations", "Decks", 210],
  ["Team Work", "Sessions", 170],
];

const DOCS = [
  "Project Abstract",
  "Problem Statement",
  "Literature Review",
  "Design Documents",
  "Block Diagrams",
  "CAD Models",
  "Simulation Results",
  "Review Presentations",
  "Research Papers",
  "Final Report",
];
